### ISSUE TITLE
MySQL 5.7 Strict Mode Error

### ISSUE THREAD

**Issue by Andrewsuares** [johnbe4/getSeoSitemap#4]
Hello,

I am seeing database errors with MySQL 5.7. I've set the default value of all the fields to NULL.

How to fix this error? Thanks.

2019-07-05 00:43:43 - Execution has been stopped because of MySQL execute error: Data truncated for column 'changefreq' at row 1.

**Comment by johnbe4** [comment]
Hi Andrew,
Do not set fields to NULL.
Please DROP getSeoSitemap and getSeoSitemapExec tables.
Use the latest release v3.9.1 and run the script.
Let me know.
Best,
John

**Comment by Andrewsuares** [comment]
Would be nice if the config variables were in a separate config.php file. Updates would be easier.

**Comment by Andrewsuares** [comment]
Seeing these errors in the latest version

[07-Jul-2019 02:01:10 America/Denver] PHP Fatal error:  Uncaught Error: Call to a member function query() on null in getSeoSitemap.php:279
Stack trace:
#0 getSeoSitemap.php(1440): getSeoSitemap->execQuery()
#1 getSeoSitemap.php(1698): getSeoSitemap->updateExec()
#2 getSeoSitemap.php(2262): getSeoSitemap->stopExec()
#3 getSeoSitemap.php(2044): getSeoSitemap->readRobots()
#4 getSeoSitemap.php(183): getSeoSitemap->prep()
#5 getSeoSitemap.php(2398): getSeoSitemap->start()
#6 {main}
  thrown in getSeoSitemap.php on line 279

PHP version 7.3.6
MySQL 5.7

**Comment by johnbe4** [comment]
Ok, about config.php file for future releases.
Send me getSeoSitemap/log/20190707.log

**Comment by Andrewsuares** [comment]
[20190707.log](https://github.com/johnbe4/getSeoSitemap/files/3365431/20190707.log)

I do have a robots.txt file

https://www.hobotraveler.com/robots.txt

**Comment by johnbe4** [comment]
Let me know the value of DOMAINURL.

**Comment by johnbe4** [comment]
Inside prep function do this:
// set execution of function to y
$this->exec = 'y';
$this->updateExec();

##########################
// check tables into dbase
//$this->checkTables();
##########################

// update all states to old to be ready for the new full scan
$this->query = "UPDATE getSeoSitemap SET state = 'old'";
$this->execQuery();

and:
// set version in userAgent
$this->userAgent = str_replace('ver.', $this->version, $this->userAgent);

#################################
//// read robots.txt
//$this->readRobots();
//
//// set $skipUrl
//$this->getRobotsData();
#################################

// open mysqli connection
$this->openMysqliConn();

#################################
// check tables into dbase
$this->checkTables();

// read robots.txt
$this->readRobots();

// set $skipUrl
$this->getRobotsData();
#################################

$this->query = "SELECT exec FROM getSeoSitemapExec WHERE func = 'getSeoSitemap' LIMIT 1";
$this->execQuery();

**Comment by Andrewsuares** [comment]
https://www.hobotraveler.com/

**Comment by johnbe4** [comment]
Set:
const DOMAINURL = 'https://www.hobotraveler.com';

**Comment by Andrewsuares** [comment]
Seeing the same error

**Comment by johnbe4** [comment]
Previous value was 'https://www.hobotraveler.com/'.
New value must be 'https://www.hobotraveler.com'.
Please confirm.

**Comment by johnbe4** [comment]
Double check the value of SITEMAPPATH.

**Comment by Andrewsuares** [comment]
Attached. The previous version worked fine with the values other than the  MySQL issue.
[config.txt](https://github.com/johnbe4/getSeoSitemap/files/3365474/config.txt)

**Comment by johnbe4** [comment]
sitemap.xml and robots.txt files must be in the same path.
The URL https://www.hobotraveler.com/sitemap.xml.gz return page not found.
The URL https://www.hobotraveler.com/robots.txt return robots.txt but it is not updated.
Double-check it and let me know

**Comment by Andrewsuares** [comment]
The sitemap doesnt exist because the new one hasnt been generated. What is the problem with robots.txt

**Comment by johnbe4** [comment]
sitemap.xml and robots.txt files must be in the same path. Just fix that.
Set the correct value of SITEMAPPATH.
The script will fix the rest automatically.

**Comment by Andrewsuares** [comment]
Now this. 

2019-07-07 04:38:00 - Execution has been stopped because of MySQL error. Error (1146): Table 'hobo.getSeoSitemapExec' doesn't exist - query: "SELECT exec FROM getSeoSitemapExec WHERE func = 'getSeoSitemap' LIMIT 1" - fix it remembering to set exec to n in getSeoSitemapExec table.

**Comment by Andrewsuares** [comment]
It appears it didnt create the tables.

**Comment by johnbe4** [comment]
Please read my previous note about prep function.

**Comment by johnbe4** [comment]
I've just updated that previous post.

**Comment by Andrewsuares** [comment]
Changed prep to below. The same error.

// set execution of function to y
$this->exec = 'y';
$this->updateExec();

// check tables into dbase
//$this->checkTables();

**Comment by johnbe4** [comment]
Read all that post.
....
and:
// set version in userAgent
$this->userAgent = str_replace('ver.', $this->version, $this->userAgent);

#################################
//// read robots.txt
//$this->readRobots();
//
//// set $skipUrl
//$this->getRobotsData();
#################################

// open mysqli connection
$this->openMysqliConn();

#################################
// check tables into dbase
$this->checkTables();

// read robots.txt
$this->readRobots();

// set $skipUrl
$this->getRobotsData();
#################################

$this->query = "SELECT exec FROM getSeoSitemapExec WHERE func = 'getSeoSitemap' LIMIT 1";
$this->execQuery();

**Comment by johnbe4** [comment]
Copy and paste the new updated prep function below:
################################################################################
private function prep(){

$time = time();

// set log path: it will remain the same from the start to the end of execution
$this->logPath = GETSITEMAPPATH.'log/'.date('Ymd', $time).'.log';

// set robots.txt path
$this->robotsPath = SITEMAPPATH.'robots.txt';

// set start time
$this->startTime = $time;

// set version in userAgent
$this->userAgent = str_replace('ver.', $this->version, $this->userAgent);

#################################
//// read robots.txt
//$this->readRobots();
//
//// set $skipUrl
//$this->getRobotsData();
#################################

// open mysqli connection
$this->openMysqliConn();

#################################
// check tables into dbase
$this->checkTables();

// read robots.txt
$this->readRobots();

// set $skipUrl
$this->getRobotsData();
#################################

$this->query = "SELECT exec FROM getSeoSitemapExec WHERE func = 'getSeoSitemap' LIMIT 1";
$this->execQuery();

// check if getSeoSitemap is already running and stop it to prevent double execution
if ($this->row[0]['exec'] === 'y') {
$this->writeLog('An error has occoured: execution has been stopped; '
.'maybe the previous scan was not ended correctly. Double-check log to fix it.'.$this->txtToAddOnMysqliErr);

exit();
}
// check if prevous full scan was ended to start a new full scan
elseif ($this->row[0]['exec'] === 'n') {
$this->writeLog('## getSeoSitemap '.$this->version);
$this->writeLog('## Execution start');
}
else {
$this->writeLog('Value of state in getSeoSitemapExec table is not correct: '
.'execution has been stopped. Double-check log to fix it.'.$this->txtToAddOnMysqliErr);

exit();
}

// set execution of function to y
$this->exec = 'y';
$this->updateExec();

##########################
// check tables into dbase
//$this->checkTables();
##########################

// update all states to old to be ready for the new full scan
$this->query = "UPDATE getSeoSitemap SET state = 'old'";
$this->execQuery();

$this->writeLog('## Scan start');

// prepare mysqli statements
$this->prepMysqliStmt();

// insert or update DOMAINURL
$this->insUpdNewUrlQuery(DOMAINURL);

$this->openCurlConn();

}
################################################################################

**Comment by Andrewsuares** [comment]
Btw, I"ve noticed that this version does not have the const STARTURL. I used to use the STARTURL parameter before because our index page doesn't have all the links. Our index page is more of a landing page. The STARTURL is required for websites like ours.

2019-07-07 05:07:22 - ## getSeoSitemap v3.9.1
2019-07-07 05:07:22 - ## Execution start
2019-07-07 05:07:22 - ## Scan start
2019-07-07 05:07:22 - H1 does not exist (SEO: h1 should be present) - URL https://www.hobotraveler.com
2019-07-07 05:07:22 - H2 does not exist (SEO: h2 should be present) - URL https://www.hobotraveler.com
2019-07-07 05:07:22 - H3 does not exist (SEO: h3 should be present) - URL https://www.hobotraveler.com
2019-07-07 05:07:22 - Image without title: https://www.facebook.com/tr?id=655035504971201&ev=PageView&noscript=1 - URL: https://www.hobotraveler.com
2019-07-07 05:07:22 - Image without alt: https://www.facebook.com/tr?id=655035504971201&ev=PageView&noscript=1 - URL: https://www.hobotraveler.com
2019-07-07 05:07:22 - Execution has been stopped because of MySQL execute error: incorrect integer value: '' for column 'lastmod' at row 1

**Comment by johnbe4** [comment]
A search engine should crawl all pages starting from the home page.
It seems there are not links into your home page and that is wrong.
You should update the structure.
My script is "getSeoSitemap".
A structure like your site is not good about Seo.
About the last MySQL execute error I'm checking a solution.

**Comment by johnbe4** [comment]
Update all log messages equal to "Execution has been stopped because of MySQL execute error".
Into scan function:
Execution has been stopped because of stmt->execute error
Into getHref:
Execution has been stopped because of stmt5->execute error
Into checkSkipUrls:
Execution has been stopped because of stmt->execute error
Into insUpdNewUrlQuery:
Execution has been stopped because of stmt2->execute error
Into scan:
Execution has been stopped because of stmt3->execute error
Into insSkipUrl:
Execution has been stopped because of stmt4->execute error
Into fullScan
Execution has been stopped because of stmt->execute error
Let me know.

**Comment by johnbe4** [comment]
To fix your old STARTURL, just add a link to your old STARTURL into your home page.

**Comment by Andrewsuares** [comment]
> 
> 
> Update all log messages equal to "Execution has been stopped because of MySQL execute error".
> Into scan function:
> Execution has been stopped because of stmt->execute error
> Into getHref:
> Execution has been stopped because of stmt5->execute error
> Into checkSkipUrls:
> Execution has been stopped because of stmt->execute error
> Into insUpdNewUrlQuery:
> Execution has been stopped because of stmt2->execute error
> Into scan:
> Execution has been stopped because of stmt3->execute error
> Into insSkipUrl:
> Execution has been stopped because of stmt4->execute error
> Into fullScan
> Execution has been stopped because of stmt->execute error
> Let me know.

I havent understood this. I see the "Execution has been stopped because of MySQL execute error" all over the script. What do I replace?

**Comment by johnbe4** [comment]
Just replace the text "Execution has been stopped because of MySQL execute error" following the list I sent you...I need to know the execute that returns the error.

**Comment by johnbe4** [comment]
Please run the new updated v3.9.2 sending me the log.

**Comment by Andrewsuares** [comment]
2019-07-08 04:08:48 - Execution has been stopped because of MySQL database connection error: php_network_getaddresses: getaddrinfo failed: Name or service not known - fix it remembering to set exec to n in getSeoSitemapExec table.

**Comment by johnbe4** [comment]
Double check:
const DBHOST
const DBUSER
const DBPASS
const DBNAME

**Comment by johnbe4** [comment]
Hi Andrew,
Did you fix?
Let me know in order to close this issue.
Best,

**Comment by Andrewsuares** [comment]
Hello John,

Been terribly busy. I will get back on this in 1-2 days. Thanks!

**Comment by Andrewsuares** [comment]
2019-07-11 11:43:26 - ## getSeoSitemap v3.9.2
2019-07-11 11:43:26 - ## Execution start
2019-07-11 11:43:26 - ## Scan start
2019-07-11 11:43:26 - H1 does not exist (SEO: h1 should be present) - URL https://www.hobotraveler.com
2019-07-11 11:43:26 - H2 does not exist (SEO: h2 should be present) - URL https://www.hobotraveler.com
2019-07-11 11:43:26 - H3 does not exist (SEO: h3 should be present) - URL https://www.hobotraveler.com
2019-07-11 11:43:26 - Image without title: https://www.facebook.com/tr?id=655035504971201&ev=PageView&noscript=1 - URL: https://www.hobotraveler.com
2019-07-11 11:43:26 - Image without alt: https://www.facebook.com/tr?id=655035504971201&ev=PageView&noscript=1 - URL: https://www.hobotraveler.com
2019-07-11 11:43:26 - Execution has been stopped because of MySQL stmt4 execute error: incorrect integer value: '' for column 'lastmod' at row 1

**Comment by johnbe4** [comment]
In checkTables function update this:
$this->query = "CREATE TABLE `getSeoSitemap` (
 `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 `url` varbinary(767) NOT NULL,
 `callerUrl` varbinary(767) DEFAULT NULL,
 `size` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'byte',
 `title` text COLLATE utf8_unicode_ci,
 `description` text COLLATE utf8_unicode_ci,
 `md5` char(32) COLLATE utf8_unicode_ci DEFAULT NULL,
 `lastmod` int(10) unsigned NOT NULL DEFAULT 0,
 `changefreq` enum('daily','weekly','monthly','yearly') COLLATE utf8_unicode_ci NOT NULL,
 `priority` enum('0.1','0.2','0.3','0.4','0.5','0.6','0.7','0.8','0.9','1.0') COLLATE utf8_unicode_ci DEFAULT NULL,
 `state` enum('new','scan','skip','rSkip','old') COLLATE utf8_unicode_ci NOT NULL,
 `httpCode` char(3) COLLATE utf8_unicode_ci DEFAULT NULL,
 PRIMARY KEY (`id`),
 UNIQUE KEY `url` (`url`),
 KEY `state` (`state`),
 KEY `httpCode` (`httpCode`),
 KEY `size` (`size`),
 KEY `changefreq` (`changefreq`),
 KEY `priority` (`priority`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci"; 

and this:
$this->query = "ALTER TABLE getSeoSitemap CHANGE size size int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'byte'; 
ALTER TABLE getSeoSitemap CHANGE md5 md5 char(32) COLLATE utf8_unicode_ci DEFAULT NULL; 
ALTER TABLE getSeoSitemap CHANGE lastmod lastmod int(10) unsigned NOT NULL DEFAULT 0; 
ALTER TABLE getSeoSitemap CHANGE httpCode httpCode char(3) COLLATE utf8_unicode_ci DEFAULT NULL;";

Drop getSeoSitemap table.
Restart the script.

**Comment by johnbe4** [comment]
I changed default values from '0' to 0.
Let me know.

**Comment by Andrewsuares** [comment]
2019-07-11 21:16:27 - ## getSeoSitemap v3.9.2
2019-07-11 21:16:27 - ## Execution start
2019-07-11 21:16:27 - ## Scan start
2019-07-11 21:16:28 - H1 does not exist (SEO: h1 should be present) - URL https://www.hobotraveler.com
2019-07-11 21:16:28 - H2 does not exist (SEO: h2 should be present) - URL https://www.hobotraveler.com
2019-07-11 21:16:28 - H3 does not exist (SEO: h3 should be present) - URL https://www.hobotraveler.com
2019-07-11 21:16:28 - Image without title: https://www.facebook.com/tr?id=655035504971201&ev=PageView&noscript=1 - URL: https://www.hobotraveler.com
2019-07-11 21:16:28 - Image without alt: https://www.facebook.com/tr?id=655035504971201&ev=PageView&noscript=1 - URL: https://www.hobotraveler.com
2019-07-11 21:16:28 - Execution has been stopped because of MySQL stmt4 execute error: incorrect integer value: '' for column 'lastmod' at row 1

**Comment by johnbe4** [comment]
Into prepMysqliStmt function update $this->stmt4 from:
$this->stmt4 = $this->mysqli->prepare("INSERT INTO getSeoSitemap ("
. "url, "
. "callerUrl, "
. "size, "
. "md5, "
. "lastmod, "
. "changefreq, "
. "priority, "
. "state, "
. "httpCode) "
. "VALUES ("
. "?, "
. "?, "
. "?, "
. "'', "
. "'', "
. "'', "
. "NULL, "
. "'skip', "
. "?) "
. "ON DUPLICATE KEY UPDATE "
. "callerUrl = ?, "
. "size = ?, "
. "md5 = '', "
. "lastmod = 0, "
. "changefreq = '', "
. "priority = NULL, "
. "state = 'skip', "
. "httpCode = ?");

to this:
$this->stmt4 = $this->mysqli->prepare("INSERT INTO getSeoSitemap ("
. "url, "
. "callerUrl, "
. "size, "
. "state, "
. "httpCode) "
. "VALUES ("
. "?, "
. "?, "
. "?, "
. "'skip', "
. "?) "
. "ON DUPLICATE KEY UPDATE "
. "callerUrl = ?, "
. "size = ?, "
. "state = 'skip', "
. "httpCode = ?");

Drop getSeoSitemap table.
Restart the script.

**Comment by Andrewsuares** [comment]
2019-07-12 00:51:28 - Execution has been stopped because of MySQL error. Error (1055): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'hobo.getSeoSitemap.description' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by - query: "SELECT description FROM getSeoSitemap WHERE state != 'skip' AND state != 'rSkip' AND httpCode = '200' AND title IS NOT NULL GROUP BY title HAVING COUNT(*) > 1" - fix it remembering to set exec to n in getSeoSitemapExec table.

**Comment by johnbe4** [comment]
Into getDuplicateDescription update $this->query from:
$this->query = "SELECT description FROM getSeoSitemap WHERE state != 'skip' AND state != 'rSkip' AND httpCode = '200' AND"
." title IS NOT NULL GROUP BY title HAVING COUNT(*) > 1";

to:
$this->query = "SELECT description FROM getSeoSitemap WHERE state != 'skip' AND state != 'rSkip' AND httpCode = '200' AND"
." description IS NOT NULL GROUP BY description HAVING COUNT(*) > 1";

Drop getSeoSitemap and getSeoSitemapExec tables.
Restart the script.

**Comment by Andrewsuares** [comment]
2019-07-12 08:12:35 - Execution has been stopped because of MySQL error. Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''v0.0.0',
 `mDate` int(10) DEFAULT NULL COMMENT 'timestamp of last mod',
 `exec`' at line 4 - query: "CREATE TABLE `getSeoSitemapExec` (
 `id` int(1) NOT NULL AUTO_INCREMENT,
 `func` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
 `version` varchar(10) COLLATE utf8_unicode_ci 'v0.0.0',
 `mDate` int(10) DEFAULT NULL COMMENT 'timestamp of last mod',
 `exec` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
 `step` int(2) NOT NULL DEFAULT '0' COMMENT 'passed step',
 `newData` varchar(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'n' COMMENT 'set to y when new data are avaialble',
 UNIQUE KEY `id` (`id`),
 UNIQUE KEY `func` (`func`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='execution of getSeoSitemap functions'" - fix it remembering to set exec to n in getSeoSitemapExec table.

**Comment by johnbe4** [comment]
Update the query to create getSeoSitemapExec to:
$this->query = "CREATE TABLE `getSeoSitemapExec` (
 `id` int(1) NOT NULL AUTO_INCREMENT,
 `func` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
 `version` varchar(10) COLLATE utf8_unicode_ci DEFAULT 'v0.0.0',
 `mDate` int(10) DEFAULT NULL COMMENT 'timestamp of last mod',
 `exec` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
 `step` int(2) NOT NULL DEFAULT '0' COMMENT 'passed step',
 `newData` varchar(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'n' COMMENT 'set to y when new data are avaialble',
 UNIQUE KEY `id` (`id`),
 UNIQUE KEY `func` (`func`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='execution of getSeoSitemap functions'";

Restart the script.

**Comment by Andrewsuares** [comment]
2019-07-12 08:31:36 - ## getSeoSitemap v3.9.2
2019-07-12 08:31:36 - ## Execution start
2019-07-12 08:31:36 - ## Scan start
2019-07-12 08:31:36 - H1 does not exist (SEO: h1 should be present) - URL https://www.hobotraveler.com
2019-07-12 08:31:36 - H2 does not exist (SEO: h2 should be present) - URL https://www.hobotraveler.com
2019-07-12 08:31:36 - H3 does not exist (SEO: h3 should be present) - URL https://www.hobotraveler.com
2019-07-12 08:31:36 - Image without title: https://www.facebook.com/tr?id=655035504971201&ev=PageView&noscript=1 - URL: https://www.hobotraveler.com
2019-07-12 08:31:36 - Image without alt: https://www.facebook.com/tr?id=655035504971201&ev=PageView&noscript=1 - URL: https://www.hobotraveler.com
2019-07-12 08:31:36 - ## Scan end

2019-07-12 08:31:36 - Deleted old URLs
2019-07-12 08:31:36 - 50 scanned URLs
2019-07-12 08:31:36 - Setted URLs to skip following robots.txt rules
2019-07-12 08:31:36 - 0 URLs without title into domain (SEO: title should be present)
2019-07-12 08:31:36 - 0 URLs with multiple title into domain (SEO: title should be single)
2019-07-12 08:31:36 - 0 URLs without description into domain (SEO: description should be present)
2019-07-12 08:31:36 - 0 URLs with multiple description into domain (SEO: description should be single)
2019-07-12 08:31:36 - 1 URLs without h1 into domain (SEO: h1 should be present)
2019-07-12 08:31:36 - 0 URLs with multiple h1 into domain (SEO: h1 should be single)
2019-07-12 08:31:36 - 1 URLs without h2 into domain (SEO: h2 should be present)
2019-07-12 08:31:36 - 1 URLs without h3 into domain (SEO: h3 should be present)
2019-07-12 08:31:45 - ##### Failed URLs out of sitemap
2019-07-12 08:31:45 - Http code 302 - URL: https://unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.js - caller URL: https://www.hobotraveler.com
2019-07-12 08:31:45 - Http code 302 - URL: https://unpkg.com/vue-router/dist/vue-router.js - caller URL: https://www.hobotraveler.com
2019-07-12 08:31:45 - ##########
2019-07-12 08:31:45 - 2 failed URLs out of sitemap

2019-07-12 08:31:45 - ##### SEO
2019-07-12 08:31:45 - ##### URLs with size > 132.00 Kb into sitemap (SEO: page size should be lower than 132.00 Kb)
2019-07-12 08:31:45 - ##########
2019-07-12 08:31:45 - 0 URLs with size > 132.00 Kb into sitemap

2019-07-12 08:31:45 - 0 URLs with title length < 5 characters into sitemap
2019-07-12 08:31:45 - 0 URLs with title length > 101 characters into sitemap

2019-07-12 08:31:45 - 0 URLs with duplicate title into sitemap
2019-07-12 08:31:45 - 0 URLs with description length < 50 characters into sitemap
2019-07-12 08:31:45 - 0 URLs with description length > 160 characters into sitemap
2019-07-12 08:31:45 - 0 URLs with duplicate description into sitemap
2019-07-12 08:31:45 - 33 URLs into domain out of sitemap

2019-07-12 08:31:45 - Setted priority 1.0 to 0 URLs into sitemap
2019-07-12 08:31:45 - Setted priority 0.9 to 0 URLs into sitemap
2019-07-12 08:31:45 - Setted priority 0.8 to 0 URLs into sitemap
2019-07-12 08:31:45 - Setted priority 0.7 to 0 URLs into sitemap
2019-07-12 08:31:45 - Setted priority 0.6 to 0 URLs into sitemap
2019-07-12 08:31:45 - Setted priority 0.5 to 1 URLs into sitemap
2019-07-12 08:31:45 - Setted daily change frequency to 1 URLs into sitemap
2019-07-12 08:31:45 - Setted weekly change frequency to 0 URLs into sitemap
2019-07-12 08:31:45 - Setted monthly change frequency to 0 URLs into sitemap
2019-07-12 08:31:45 - Setted yearly change frequency to 0 URLs into sitemap
2019-07-12 08:31:45 - Min last modified time into sitemap is 2019.07.12 08:31:36
2019-07-12 08:31:45 - Max last modified time into sitemap is 2019.07.12 08:31:36

2019-07-12 08:31:45 - Saved sitemap.xml
2019-07-12 08:31:45 - Saved sitemap.xml.gz
2019-07-12 08:31:45 - Deleted sitemap.xml
2019-07-12 08:31:45 - Wrote robots.txt

2019-07-12 08:31:45 - ################################
2019-07-12 08:31:45 - Included 1 URLs into sitemap
2019-07-12 08:31:45 - ################################

2019-07-12 08:31:45 - 16 URLs out of domain out of sitemap
2019-07-12 08:31:45 - 0 URLs with malformed characters into domain

2019-07-12 08:31:45 - Optimized getSeoSitemap table
2019-07-12 08:31:45 - Total execution time 00:00:09
2019-07-12 08:31:45 - ##### Execution end

**Comment by Andrewsuares** [comment]
What would happen if I set the start as some other URL? Also, seems like by default this array does not exist.

##### start of user parameters
private $skipUrl = [ // skip all urls that start or are equal these values (values must be absolute)
'https://www.facebook.com/',
'http://pinterest.com/',
];

**Comment by johnbe4** [comment]
You must add a link to your old STARTURL into your home page.
That is very very important for users and search engines.
In that way the script and all visitors will be able to surf all your site.

**Comment by johnbe4** [comment]
You must do that!

**Comment by Andrewsuares** [comment]
OK thanks. I thought this version didnt support the array parameters. Where exactly should I set the array? Which line?

**Comment by johnbe4** [comment]
You should use robots.txt to do that.
Search engines follow robots.txt rules and my script does the same now.

**Comment by johnbe4** [comment]
Use Disallow command in robots.txt.
Can I close this issue?

**Comment by Andrewsuares** [comment]
Yes, thanks for the fixes! I guess these will be in the new version.

**Comment by johnbe4** [comment]
Inside robots.txt you don't have to disallow external domain...only URLs into domain.
Ext URLs will be skipped automatically.
I'm preparing the new version 3.9.3.
Best,
